version: '3'
services:
  guacamole:
    image: flcontainers/guacamole
    environment:
      TZ: 'Europe/Vilnius'
      EXTENSIONS: 'auth-totp,auth-ldap'
    volumes:
      - ssh_guacamole_nfs:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8084:8080
volumes:
  ssh_guacamole:
    external: true
  ssh_guacamole_nfs:
    driver_opts:
      type: nfs
      o: addr=192.168.0.10,rw,nolock,hard,nointr,nfsvers=3
      device: ":/mnt/main/docker-volumes/guacamole"
