version: '3'
services:
  guacamole:
    image: flcontainers/guacamole
    container_name: guacamole
    environment:
      TZ: 'Europe/Vilnius'
      EXTENSIONS: 'auth-totp,auth-ldap'
    volumes:
      - ssh_guacamole:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8084:8080
    restart: unless-stopped
volumes:
  ssh_guacamole:
    external: true

