version: '3.8'
services:
  nginx_manager:
    container_name: nginx-proxy
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8085:80'
      - '8183:81'
      - '5443:443'
    volumes:
      - /mnt/nginx-data/data:/data
      - /mnt/nginx-data/letsencrypt:/etc/letsencrypt
    deploy:
      placement:
        constraints:
          - node.role == manager 
volumes:
  proxy_data:
    driver_opts:
      type: nfs
      o: addr=192.168.0.10,rw,nolock,hard,nointr,nfsvers=3
      device: ":/mnt/main/docker-volumes/nginx-proxy/data"
  proxy_letsencrypt:
    driver_opts:
      type: nfs
      o: addr=192.168.0.10,rw,nolock,hard,nointr,nfsvers=3
      device: ":/mnt/main/docker-volumes/nginx-proxy/letsencrypt"
