version: "3.3"
services:
  documentserver:
    stdin_open: true
    tty: true
    # restart: always
    volumes:
      - logs:/var/log/onlyoffice
      - data:/var/www/onlyoffice/Data  
      - lib:/var/lib/onlyoffice 
    image: onlyoffice/documentserver
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.documentserver.entrypoints=http"
      - "traefik.http.routers.documentserver.rule=Host(`docs.phoenixonline.club`)"
      - "traefik.http.middlewares.documentserver-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.documentserver.middlewares=documentserver-https-redirect"
      - "traefik.http.routers.documentserver-secure.entrypoints=https"
      - "traefik.http.routers.documentserver-secure.rule=Host(`docs.phoenixonline.club`)"
      - "traefik.http.routers.documentserver-secure.tls=true"
      - "traefik.http.routers.documentserver-secure.service=documentserver"
      - "traefik.http.services.documentserver.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik-public"
    deploy:
      mode: global
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true


volumes:
  data:
    driver_opts:
      type: nfs
      o: addr=192.168.0.10,rw,nolock,hard,nointr,nfsvers=3
      device: ":/mnt/main/docker-volumes/onlyoffice/data"
  logs:
    driver_opts:
      type: nfs
      o: addr=192.168.0.10,rw,nolock,hard,nointr,nfsvers=3
      device: ":/mnt/main/docker-volumes/onlyoffice/logs"
  lib:
    driver_opts:
      type: nfs
      o: addr=192.168.0.10,rw,nolock,hard,nointr,nfsvers=3
      device: ":/mnt/main/docker-volumes/onlyoffice/lib"

