apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher
  namespace: cattle-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher
  template:
    metadata:
      labels:
        app: rancher
    spec:
      containers:
      - name: rancher
        image: rancher/rancher:v2.8 # Replace with the desired Rancher version
        ports:
        - containerPort: 80
        env:
        - name: CATTLE_SYSTEM_CATALOG
          value: library
        - name: CATTLE_NAMESPACES
          value: "true"
