apiVersion: v1
kind: Service
metadata:
  name: rancher
  namespace: cattle-system
spec:
  selector:
    app: rancher
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
  type: LoadBalancer
