version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
    volumes:
      - radarr_data:/config
      - /mnt/media/films:/films #optional
      - /mnt/media/downloads:/downloads #optional
    restart: unless-stopped
    ports:
      - 9696:9696
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
    volumes:
      - prowlarr_data:/config
    restart: unless-stopped
    ports:
      - 7878:7878
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
    volumes:
      - sonarr_data:/config
      - /mnt/media/shows:/tv #optional
      - /mnt/media/downloads:/downloads #optional
    restart: unless-stopped
    ports:
      - 8989:8989
volumes:
  radarr_data:
    driver_opts:
      type: nfs
      o: addr=192.168.0.10,rw,nolock,hard,nointr,nfsvers=3
      device: ":/mnt/main/docker-volumes/radarr"
  prowlarr_data:
    driver_opts:
      type: nfs
      o: addr=192.168.0.10,rw,nolock,hard,nointr,nfsvers=3
      device: ":/mnt/main/docker-volumes/prowlarr"
  sonarr_data:
    driver_opts:
      type: nfs
      o: addr=192.168.0.10,rw,nolock,hard,nointr,nfsvers=3
      device: ":/mnt/main/docker-volumes/sonarr"
