version: "3"
services:
  portainer:
    image: portainer/agent:latest
    container_name: portainer_agent
    ports:
      - 9001:9001
    volumes:
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
