- name: install software 
  hosts: "desktop"
  become: true
  tasks:
    - name: install git
      pacman:
        name: git
        state: present
        update_cache: true
 
    - name: install base-devel
      pacman:
        name: base-devel
        state: present
        update_cache: true

    - name: install nerd-fonts
      pacman:
        name: ttf-nerd-fonts-symbols
        state: present
        update_cache: true

    - name: install lightdm
      pacman:
        name: lightdm        
        state: present
        update_cache: true

    - name: install nfs-utils
      pacman:
        name: nfs-utils        
        state: present
        update_cache: true

    - name: install starship 
      shell: sh -c "$(curl -fsSL https://starship.rs/install.sh)" 



- name: mounting some stuff
  hosts: "desktop"
  become: true
  tasks:
    - name: mount point to access my configs
      shell: mount -t nfs 10.0.0.1:/home/karl /mnt
    
    - name: change permission of config
      shell: chmod -R 777 /home/karl/.config

- name: copy some of my configs    
  hosts: "desktop"
  become : true
  tasks:
    - name: zshrc copy  
      shell: cp /mnt/.zshrc /home/karl
    
    - name: neovim copy
      shell: cp -r /mnt/.config/nvim /home/karl/.config
    
    - name: starship copy      
      shell: cp -r /mnt/.config/starship.toml /home/karl/.config
    
    - name: copy oh my zsh     
      shell: cp -r /mnt/.config/oh-my-zsh /home/karl/.config/
    
    
- name: mounting some more stuff
  hosts: "desktop"
  become: true
  tasks:
    - name: umount the config path 
      shell: umount /mnt

    - name: mount point to access my configs
      shell: mount -t nfs 10.0.0.1:/media/cloud_storage /mnt

    
- name: copying some more config files
  hosts: "desktop"
  become: true
  tasks:
    - name: copy qtile
      shell: cp -r /mnt/Yandex.Disk/ansible/files/qtile /home/karl/.config/
    
    - name: copy tmux folder
      shell: cp -r /mnt/Yandex.Disk/ansible/files/tmux/.tmux /home/karl/ 

    - name: copy tmux local file
      shell: cp -r /mnt/Yandex.Disk/ansible/files/tmux/.tmux.conf.local /home/karl/ 
    
    - name: linking tmux.conf
      shell: ln /home/karl/.tmux/.tmux.conf /home/karl/.tmux.conf 

    
- name: doing some random stuff
  hosts: "desktop"
  become: true
  tasks:
    - name: set zsh as default 
      shell: usermod -s /usr/bin/zsh karl
   
    - name: copy lightdm configs
      shell: cp /mnt/Yandex.Disk/ansible/files/lightdm/* /etc/lightdm/
    
    - name: change permission of home user folder   
      shell: chown -R karl:karl /home/karl/
    
    - name: change permission of config folder  
      shell: chmod 700 /home/karl/.config





