- name: configure the users homefolder
  hosts: "desktop"
  become: yes
  tasks:
    - name: mount point to access my configs
      shell: mount -t nfs 10.0.0.1:/home/karl /mnt

    - name: zshrc copy  
      shell: cp /mnt/.zshrc /home/karl
    
    - name: neovim copy
      shell: cp -r /mnt/.config/nvim
    
    - name: starship copy      
      shell: cp -r /mnt/.config/starship.toml
    
    - name: copy oh my zsh     
      shell: cp -r /mnt/.config/oh-my-zsh /home/karl/.config/
    
    - name: make script folder
      shell: mkdir /home/karl/.script

    - name: make dmenu folder
      shell: mkdir /home/karl/.dmenu

    - name: set zsh as default 
      shell: usermod -s /usr/bin/zsh karl
   
    - name: change owner of karl homefolder  
      shell: chown -R karl:karl /home/karl

    - name: umount the config path 
      shell: umount /mnt


- name: configure desktop specific tasks
  hosts: "desktop"
  become: true
  tasks: 
    - name: mount my cloud folder
    - shell: mount -t nfs 10.0.0.1:/media/cloud_storage /mnt  

    - name: install my packages
    - shell: pacman -S $(cat /mnt/Yandex.Disk/Backups/package_list/pac.packages.txt | grep -v nvidia)  

    - name: install paru  
    - shell: git clone   

