- name: install starship prompt
  hosts: "*"
  become: true
  tasks: 
    - name: install starship 
      shell: sh -c "$(curl -fsSL https://starship.rs/install.sh)" 



- name: install software
  hosts: "fedora"
  become: true
  tasks:
    - name: install zsh
      dnf:
        name: zsh
        state: present
        update_cache: true

    - name: install fish
      dnf:
        name: fish
        state: present
        update_cache: true
    
    - name: install nfs-utils
      dnf:
        name: nfs-utils
        state: present
        update_cache: true
   
    - name: install git
      dnf:
        name: git
        state: present
        update_cache: true
   
    - name: install nvim
      dnf:
        name: neovim
        state: present
        update_cache: true

    - name: install autofs
      dnf:
        name: autofs
        state: present
        update_cache: true

    - name: install tmux
      dnf:
        name: tmux
        state: present
        update_cache: true

    - name: install ssh
      dnf:
        name: openssh-server
        state: present
        update_cache: true


- name: install software
  hosts: "ubuntu"
  become: true
  tasks:
    - name: install zsh
      apt:
        name: zsh
        state: present
        update_cache: true

    - name: install fish
      apt:
        name: fish
        state: present
        update_cache: true       
    
    - name: install nfs-common
      apt:
        name: nfs-utils
        state: present
        update_cache: true
   
    - name: install git
      apt:
        name: git
        state: present
        update_cache: true
   
    - name: install nvim
      apt:
        name: neovim
        state: present
        update_cache: true       

    - name: install autofs
      apt:
        name: autofs
        state: present
        update_cache: true       

    - name: install tmux
      apt:
        name: tmux
        state: present
        update_cache: true       

    - name: install ssh
      apt:
        name: openssh-server
        state: present
        update_cache: true       

- name: install software 
  hosts: "desktop"
  become: true
  tasks:
    - name: install git
      pacman:
        name: git
        state: present
        update_cache: true
 
    - name: install base-devel
      pacman:
        name: base-devel
        state: present
        update_cache: true

    - name: install nerd-fonts
      pacman:
        name: ttf-nerd-fonts-symbols
        state: present
        update_cache: true

    - name: install lightdm
      pacman:
        name: lightdm        
        state: present
        update_cache: true

    - name: install nfs-utils
      pacman:
        name: nfs-utils        
        state: present
        update_cache: true


   
