- name: install software
  hosts: "ubuntu"
  become: true
  tasks:
    - name: install zsh
      apt:
        name: zsh
        state: present
        update_cache: true

    - name: install fish
      apt:
        name: fish
        state: present
        update_cache: true       
    
    - name: install nfs-common
      apt:
        name: nfs-utils
        state: present
        update_cache: true
   
    - name: install git
      apt:
        name: git
        state: present
        update_cache: true
   
    - name: install nvim
      apt:
        name: neovim
        state: present
        update_cache: true       

    - name: install autofs
      apt:
        name: autofs
        state: present
        update_cache: true       

    - name: install tmux
      apt:
        name: tmux
        state: present
        update_cache: true       


