---
  - name: Config files configuration
    hosts: debian
    roles:
      - role: gantsign.oh-my-zsh
        users:
          - username: karl
            oh_my_zsh: 
              theme: af-magic 
              plugins:
                - git 
                - mvn 
    tasks:
      - name: ensures git is installed
        become: true
        apt:
          name: git
          state: latest  
          update_cache: true
      - name: ensures bat is installed
        become: true
        apt:
          name: bat
          state: latest  
          update_cache: true
      - name: ensures wget is installed 
        become: true
        apt:
          name: wget
          state: latest  
          update_cache: true
      - name: ensures zsh is installed 
        become: true
        apt:
          name: zsh
          state: latest  
          update_cache: true
            
      - name: clones my dotfiles directory
        git:
          clone: yes
          dest: /home/karl/dotfiles  
          repo: https://github.com/phoenix988/dotfiles.git  
      - name: download starship script      
        get_url:
          dest: /home/karl
          url:  https://raw.githubusercontent.com/phoenix988/setup/main/starship.sh
      - name: install starship       
        become: true
        shell:  
          cmd: sh starship.sh -y
      - name: Creating folder Documents/lists       
        file:  
          state: directory      
          dest: Documents/lists
      - name: getting my zshrc file      
        get_url:  
          dest: /home/karl/.zshrc 
          url: https://raw.githubusercontent.com/phoenix988/dotfiles/main/.zshrc
      - name: install oh my zsh plugin syntax-highlighting
        git:
          clone: yes
          dest: /home/karl/.config/oh-my-zsh/zsh-syntax-highlighting  
          repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      - name: install oh my zsh plugin autosuggestions
        git:
          clone: yes
          dest: /home/karl/.config/oh-my-zsh/zsh-autosuggestions  
          repo:  https://github.com/zsh-users/zsh-autosuggestions.git
      - name: gets my alias list and add it to Documents/lists
        get_url:
          dest: /home/karl/Documents/lists/
          url: https://raw.githubusercontent.com/phoenix988/dotfiles/main/Documents/lists/alias.list
      - name: copying my script folder      
        shell:
          cmd: cp -r /home/karl/dotfiles/.scripts /home/karl/
      - name: copying my dmenu folder      
        shell:
          cmd: cp -r /home/karl/dotfiles/.dmenu /home/karl/
      - name: copying my aliases to zsh
        shell:
          cmd: cp Documents/lists/alias.list  .config/oh-my-zsh/aliases.sh
      - name: linking my scripts to /usr/bin
        become: true
        file:
          state: link
          src: /home/karl/.scripts/activated  
          dest: /usr/bin/myscripts  

