- name: Updating Servers
  become: yes
  hosts: cluster
  tasks:
    - name: Running apt dist-upgrade
      apt:
        upgrade: dist
    - name:
      apt:
        name: unattended-upgrades
        state: present


 

 
