---
version: "3.8"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
      - JELLYFIN_PublishedServerUrl=example.com #optional
    volumes:
      - jellyfin_config_nfs:/config
      - /mnt/media/shows:/data/tvshows
      - /mnt/media/films:/data/movies
    ports:
      - 8097:8096
      - 8921:8920 #optional
      - 7360:7359/udp #optional
      - 1901:1900/udp #optional
    restart: unless-stopped

volumes:
  jellyfin_config_nfs:
    driver_opts:
      type: nfs
      o: addr=192.168.0.10,rw,nolock,hard,nointr,nfsvers=3
      device: ":/mnt/main/docker-volumes/jellyfin"
