---
version: "3.8"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
      - JELLYFIN_PublishedServerUrl=jelly.phoenixonline.club #optional
    volumes:
      - jellyfin_conf_local:/config
      - /mnt/media/shows:/data/tvshows
      - /mnt/media/films:/data/movies
    ports:
      - 8097:8096
      - 8921:8920 #optional
      - 7360:7359/udp #optional
      - 1901:1900/udp #optional
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"
        - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.phoenixonline.club`)"
        - "traefik.http.services.jellyfin.loadbalancer.server.port=8097"

volumes:
  jellyfin_conf_local:
