services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - config:/app/data/configs
      - icons:/app/public/icons
      - data:/data
    ports:
      - '7575:7575'
      - '8443:7575'
volumes:
  config:
    driver: local
  icons: 
    driver: local
  data:
    driver: local
