apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-proxy-data-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi  # Adjust the storage size as needed

