apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-proxy-letsencrypt-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # Adjust the storage size as needed

