---
apiVersion: v1
kind: Service
metadata:
  namespace: download
  name: prowlarr
spec:
  selector:
    app: prowlarr
  ports:
    - name: http
      protocol: TCP
      port: 9696
      targetPort: 9696
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: download
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/transmission:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Vilnius"
        - name: vpn
          image: ghcr.io/bubuntux/nordvpn
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          env:
            - name: TOKEN
              value: "token"
            - name: CONNECT
              value: "Sweden"
            - name: TECHNOLOGY
              value: "NordLynx"
            - name: NETWORK
              value: "192.168.0.0/24"
          ports:
            - containerPort: 8080
            - containerPort: 9696

---
# Add similar sections for other services (overseerr, radarr, prowlarr, sonarr)

