apiVersion: v1
kind: Pod
metadata:
  name: transmission-vpn-pod
  namespace: download
spec:
  initContainers:
  - name: set-up-vpn
    image: ghcr.io/bubuntux/nordvpn
    command: ["sleep", "infinity"]  # Keep the init container running
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
          - NET_RAW
  containers:
  - name: vpn
    image: ghcr.io/bubuntux/nordvpn
    env:
    - name: TOKEN
      value: "token"
    - name: CONNECT
      value: "Sweden"
    - name: TECHNOLOGY
      value: "NordLynx"
    - name: NETWORK
      value: "192.168.0.0/24"
    ports:
    - containerPort: 8080
    - containerPort: 9091
  - name: transmission
    image: lscr.io/linuxserver/transmission:latest
    env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: TZ
      value: "Europe/Vilnius"
    - name: USER
      value: "user"
    - name: PASS
      value: "pass"
    volumeMounts:
    - name: transmission-config
      mountPath: "/config"
    - name: films
      mountPath: "/films"
    - name: shows
      mountPath: "/shows"
    - name: downloads
      mountPath: "/downloads"
  volumes:
  - name: transmission-config
    emptyDir: {}
  - name: films
    hostPath:
      path: "/mnt/media/films"
  - name: shows
    hostPath:
      path: "/mnt/media/shows"
  - name: downloads
    hostPath:
      path: "/mnt/media/downloads"

