- name: Addingfolders
  hosts: cluster
  become: yes
  tasks:
    - name: Ensure /etc/ntfy folder exists
      file:
        path: /etc/ntfy
        state: directory
    - name: Ensure /data/compose/33/data folder exists
      file:
        path: /data/compose/33/data
        state: directory

 
