version: '3'
services:
  proxy:
    container_name: nginx-proxy
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8494:80'
      - '8180:81'
      - '4443:443'
    volumes:
      - /mnt/nginx-data/data:/data
      - /mnt/nginx-data/letsencrypt:/etc/letsencrypt


