version: '3.8'
services:
  app:
    container_name: nginx-proxy
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /mnt/nginx-data/data:/data
      - /mnt/nginx-data/letsencrypt:/etc/letsencrypt
