version: "3"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:z
    restart: unless-stopped
volumes:
  portainer_data:
    driver: local
