---
version: "3.8"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - SERVERURL=wireguard.phoenixonline.club
      - TZ=Europe/Vilnius
      - SERVERPORT=51820 
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - LOG_CONFS=true #optional
    volumes:
      - wireguard_config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    deploy:
      mode: global

volumes:
  wireguard_config:
     driver_opts:
      type: nfs
      o: addr=192.168.0.10,rw,nolock,hard,nointr,nfsvers=4
      device: ":/mnt/main/docker-volumes/wireguard"
