---
  - name: clones my dotfiles directory
    git:
      clone: yes
      dest: /home/karl/dotfiles  
      repo: https://github.com/phoenix988/dotfiles.git 
  - name: zsh plugin autosuggestion
    git:
      clone: yes
      dest: /home/karl/.config/oh-my-zsh/zsh-autosuggestions  
      repo: https://github.com/zsh-users/zsh-autosuggestions.git
  - name: zsh plugin syntax-highlighting 
    git:
      clone: yes
      dest: /home/karl/.config/oh-my-zsh/zsh-syntax-highlighting  
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
  - name: installs oh-my-tmux cloning 
    git:
      clone: yes
      dest: /home/karl/.tmux
      repo: https://github.com/gpakosz/.tmux.git
  - name: installs oh-my-tmux linking config
    file:
      state: link
      src: .tmux/.tmux.conf  
      dest: .tmux.conf  
  - name: installs oh-my-tmux making conf.local      
    shell:
      cmd: cp .tmux/.tmux.conf.local .

...
