---
  - name: configure your dns server
    hosts: debian
    tasks:
      - name: install openresolv
        become: true
        apt:
          name: openresolv
          state: latest  
          update_cache: true  
      - name: modifying resolvconf.conf      
        become: true
        lineinfile:  
          state: present
          create: yes  
          line: resolvconf=NO
          path: /etc/resolvconf.conf  
      - name: set dns server to my local dns
        become: true
        template:
          src: /etc/resolv.conf
          dest: /etc/resolv.conf
      - name: stop systemd-resolved      
        become: true
        systemd:
          name: systemd-resolved
          state: stopped
          enabled: no  


