---
  - name: moving my ssh key to target server 
    ansible.posix.authorized_key:
      user: karl
      state: present
      key: "{{ lookup('file', '/home/karl/.ssh/id_rsa.pub') }}"
      path: /home/karl/.ssh/authorized_keys
      manage_dir: False

  - name: moving my ssh key to target server 
    become: true
    ansible.posix.authorized_key:
      user: karl
      state: present
      key: "{{ lookup('file', '/home/karl/.ssh/id_rsa.pub') }}"
      path: /etc/ssh/authorized_keys/karl
      manage_dir: False
