---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: media
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:latest
        ports:
        - containerPort: 8096
        volumeMounts:
        - name: jellyfin-data
          mountPath: /config
        - name: media
          mountPath: /data/media
      volumes:
      - name: jellyfin-data
        hostPath:
          path: /mnt/docker-volumes/jellyfin
      - name: media 
        hostPath:
          path: /mnt/media
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media
spec:
  type: LoadBalancer
  selector:
    app: jellyfin
  ports:
  - name: http
    protocol: TCP
    port: 8096
    targetPort: 8096
    nodePort: 30196


