apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # Adjust the storage size as needed

