# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: mariadb
    image: mariadb
    restart: always
    ports: 
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_DATABASE: nextcloud
      MARRIADB_USER: user
      MARIADB_USER_PASSWORD: pass
    volumes: 
      - mariadb_data:/var/lib/mysql

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
    volumes:
      - /mnt/nextcloud-data/config:/config
      - /mnt/nextcloud-data/data:/data
    ports:
      - 443:443
    restart: unless-stopped
volumes:
  mariadb_data:
    driver: local
